### ISSUE TITLE
D1 and D2 values not listed

### ISSUE THREAD

**Issue by trs-eric** [BasicCode/Toshiba-T1200-PSU#2]
D1 and D2 are not labeled on the schematic as to their recommended values. Not sure which diode goes where.

**Comment by BasicCode** [comment]
I intend to do an update soon with some output protection and better input protection, and I will resolve this issue then. 
In the meantime; the values for D1 and D2 don't matter too much. They both need to be Schottky type diodes with a reverse voltage of at least 30V. D1 needs to be able to handle at least 2A current (see note under Input / Output Protection).

**Comment by trs-eric** [comment]
Sounds great, thanks! Another issue I noticed, and I'm not sure if this requires a new issue, but I built five of these and all 5 had an issue with the fuse not flowing properly. I think the fuse footprint may be wrong. Otherwise they worked great and brought two machines back to life :) Thanks!

**Comment by BasicCode** [comment]
Thanks for the feedback! I'm glad to hear the project is helping. :) I discovered a fault with mine where fuse blew after being left unused for an extended period. Hopefully it was just inrush current and can be fixed with a fusable resistor but I'll do some investigation, then a board revision.

**Comment by trs-eric** [comment]
oh too bad. I haven't seen any issues so far. Let us know if you come up with a bodge for the current revision

**Comment by BasicCode** [comment]
Fixed in commit https://github.com/BasicCode/Toshiba-T1200-PSU/commit/82d8209bb4b3c766f32ac45ca0579c6cf8cf03bb
